name: Python Docker CI/CD

on:
  push:
    branches:
      - master

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Stage 1 - Verify secrets
    - name: Verify variables
      run: |
        echo "User=${{ secrets.DOCKER_USERNAME }}"
        echo "User=${{ secrets.DOCKER_PASSWORD }}"

